### ISSUE TITLE
lens.summarise(df) hangs

### ISSUE THREAD

**Issue by rmeehan** [ASIDataScience/lens#22]
As discussed with Victor here - https://twitter.com/zblz/status/938842567160066049
Running on MacBook Pro, Sierra 10.12.6
See attached PDF export from Jupyter notebook that reproduces the issue for me.
[problem_demo.pdf](https://github.com/ASIDataScience/lens/files/1541947/problem_demo.pdf)

**Comment by zblz** [comment]
I was having trouble reproducing this bug because I was using a conda installation, but after some more investigation found out it's an incompatibility between the underlying BLAS library used by numpy and multiprocessing (see [a stack overflow question](https://stackoverflow.com/questions/23963997/python-child-process-crashes-on-numpy-dot-if-pyside-is-imported) and numpy/numpy#4776).

Workarounds for the problem are:

1) Install a numpy binary compiled against a different BLAS library than Apple Accelerate (e.g., conda numpy compiled against MKL)
2) If running Python 3, run the following snippet before importing lens:
```python
import multiprocessing as mp
mp.set_start_method('spawn')
```
3) Use either the threaded or synchronous dask scheduler in lens by calling `lens.summarise` with the `scheduler='threaded'` argument:
```python
ls = lens.summarise(df, scheduler='threaded')
```

I'll close this issue as there is not much we can do in the lens code base to resolve it. Thanks for reporting it, @rmeehan!
